### ISSUE TITLE
preview should not execute html-code of txt-documents

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#24] opened 2021-11-28 12:25 UTC
Steps to reproduce
Add the following code in a txt-document somewhere on the first page:
 ```
<body style="background:gray">
```
Result: The background of Preview is gray.

Expectation
Preview should not execute html-code of txt-documents. In the browser Firefox and in the browser Web html-code of txt-documents is not executed.

**Comment by xiota** [comment] 2021-11-28 16:52
What is the name of the file?  It is probably being detected as a different filetype.  I'll check if there's some other issue.

**Comment by ralf3u** [comment] 2021-11-28 18:39
>What is the name of the file?

The name of the txt-document is geany_test.txt.

**Comment by xiota** [comment] 2021-11-28 18:45
Plain text documents are not supposed to show up in the preview (because they're just a duplicate of what's in the editor).  So there's something wrong with filetype detection.

**Comment by ralf3u** [comment] 2021-11-28 19:26
>... there's something wrong with filetype detection.

Should I do something?
All my txt-documents are shown in the Preview.

**Comment by xiota** [comment] 2021-11-28 19:46
I just checked the code.  Apparently I changed it at some point to show in the preview.  I am looking into fixing it and will update the PPA soon

**Comment by ralf3u** [comment] 2021-11-28 19:56
>... will update the PPA soon

Well, as I mentioned before, it is not necessary because I wanted to use the auto-sidebar anyway.

**Comment by xiota** [comment] 2021-11-28 20:04
> Well, as I mentioned before, it is not necessary because I wanted to use the auto-sidebar anyway.

Okay.  Will update when it's done.  (Pretty much already done, but has performance issues.)

**Comment by xiota** [comment] 2021-11-28 22:38
Fixed in 6a6f7c8a167de859135fa95a16e8141b43582331.

**Closed by xiota** 2021-11-28 22:38 UTC

**Comment by ralf3u** [comment] 2021-11-29 07:51
>Fixed in 6a6f7c8.

I can confirm.
