### ISSUE TITLE
XHTML-document does not appear in the preview

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#31] opened 2022-01-21 20:39 UTC
Geany Preview uses WebKit. The browser Web (https://wiki.gnome.org/Apps/Web) uses also WebKit. In the browser Web I can see the content of the document index.xhtml, but not in Geany Preview.

The content of index.xhtml:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>homepage</title>
</head>
<body>
	<div>some content here...</div>
</body>
</html> 
```

It seems to be that Geany Preview has no XML-parser.

**Comment by xiota** [comment] 2022-06-10 16:37
It seems to work on my computer.  Can you add a screenshot of what happens on yours?  Thank you.

**Comment by ralf3u** [comment] 2022-06-10 18:06
>It seems to work on my computer. Can you add a screenshot of what happens on yours?

Yes, now it seems to work.  There is only one white bracket (the bracket that shows to the right) that is located on the top left corner of preview. I don't know where that comes from.
Do you still want a screenshot?

**Comment by xiota** [comment] 2022-06-10 20:50
I don't need a screenshot.   The `>` appears on my screen too.  I don't know if it's caused by some processing the plugin is doing or the webkit view.  It would take more time than I want to spend right now to figure out.  I think it should be opened as a different issue, so I'm closing this one.

**Closed by xiota** 2022-06-10 20:50 UTC
Labels: cannot reproduce
