### ISSUE TITLE
content of the Preview-tab is shaking when editing fountain-documents with snippet_fountain=true

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#18] opened 2021-11-19 14:09 UTC
Steps to reproduce
- In preview.conf: snippet_fountain=true; then Edit, Plugin Preferences, Preview, Reload, Apply, OK.
- Open a fountain-document like Big Fish.
- Edit the text in the editor.

Result
The content of the Preview-tab is shaking.

Expectation
The content of the Preview-tab should not shake when editing fountain-documents.

Remark
The content of the Preview-tab does not shake when editing documents in txt, md or html.

**Comment by ralf3u** [comment] 2021-11-21 16:55
I recognized today that this behavior does also exist with a very long html-document when typing extremely fast with this setting: `snippet_html=false`. But with `snippet_html=true` there is no shaking.

It seems to be that it is too much work for the processor. But nevertheless the Preview-tab should not shake.

**Comment by ralf3u** [comment] 2021-11-24 14:01
Maybe those thoughts could help to find a solution:

What about the idea to put changes above each other, instead of replacing each time the content. Or, instead of putting all layers above each other, to use only two layers, the old layer and the new layer, so the old content and the new content, so that it will no shake any more.

For me, from all open issues at the moment, this is the most important issue, because it disturbs too much.

**Comment by xiota** [comment] 2021-11-24 20:31
@ralf3u I will start looking into this issue now.

**Comment by xiota** [comment] 2021-11-24 22:57
It looks like the problem is when the CSS is directly embedded in the HTML (no shaking) vs when the CSS file is externally linked (shaking).  CSS will be embedded when native Fountain and HTML processing is used.

Fixed in 2a01f81f0e68a74a0a775b0fd90abd1b9a56c3b1.  PPA will be updated.

**Closed** 2021-11-24 22:57 UTC
Labels: bug, wontfix, Legacy 0.1.x

**Comment by ralf3u** [comment] 2021-11-25 13:58
I made different tests with fountain, md and html with those settings:

snippet_html=true
snippet_markdown=true
snippet_fountain=true
extra_css=extra-media.css & extra_css=disable
no background color in the html

I can confirm that this issue was fixed with the settings above.
Thank you so much for that feature.

**Comment by xiota** [comment] 2021-11-25 14:34
@ralf3u Thanks for confirming.
